name: Release Latest Tag
run-name: Release version ${{ github.ref_name }} triggered by @${{ github.actor }}
on:
  release:
    types: [published]
jobs:
  build_app:
    name: Build App
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout
      - uses: actions/setup-go@v6
        name: Install Go
        with:
          go-version: '^1.25'
      - name: Build
        run: |
          brew install portaudio
          go build -o record-anywhere .
          tar -czf record-anywhere-${{ github.ref_name }}-darwin-arm64.tar.gz record-anywhere
      - uses: softprops/action-gh-release@v2
        with:
          files: record-anywhere-${{ github.ref_name }}-darwin-arm64.tar.gz
